### ISSUE TITLE
Pioneer Natural Resources: possible data bug?

### ISSUE THREAD

**Issue by mkriss** [Geofinancial/methanescan#12]
In Carto, most if not all of Pioneer's wellheads show as inactive but are still emitting. Is that accurate? Also no wellheads are shown for the Permian where it still have active sites according to this article:

https://www.bizjournals.com/houston/news/2019/05/07/houston-based-e-p-startup-buys-assets-from-pioneer.html 

Also, does our dataset accurately reflect asset sale noted in article above?

**Comment by dhald** [comment]
Hi Mark,

I’m looking into this right now.

Best,
Daniel

**Comment by mkriss** [comment]
👍

<https://app.grooveapp.com/url/vlwg4ipq99htj15whobad/aHR0cHM6Ly9nZW9maW5hbmNpYWwuY29tL2NvbW11bml0eS8%3D>

*Mark Kriss  *|  CEO  |  Geofinancial Analytics
<https://app.grooveapp.com/url/vlwg4ipq99htj15whobad/aHR0cHM6Ly9nZW9maW5hbmNpYWwuY29tL2NvbW11bml0eS8%3D>
  |  +1 612.222.9195 x3

**Comment by dhald** [comment]
Hi Mark,

I’ve figured out what the problem is and will be sending an updated dataset
to Nat momentarily. Let’s discuss the details during our call today.

Best,
Daniel

**Comment by mkriss** [comment]
Ok, great.

**Comment by mkriss** [comment]
Nat,

Daniel has fixed this in his dataset. Please update Carto. Data files are in this Box directory: https://geofinancialanalytics.box.com/s/x2e3nx5p24udlsoxqxepqjhnyrhyerbg

It would be ideal if you could fix this by end-of-day Wednesday.

Thanks!

**Comment by npspringer** [comment]
Okay.  One additional option would be to make a widget so you can toggle active/inactive wells.  Would this be useful?

**Comment by mkriss** [comment]
Yes, I like the toggle idea!

**Comment by npspringer** [comment]
New dataset uploaded. 

Tried the toggle for active/inactive, but for some reason was showing 4 options, with 2 active and 2 inactive categories.  Might be a whitespace issue, I'll check the dataset and see if I can fix from Carto.

**Comment by mkriss** [comment]
I like addition of timestamp to rollover details (e.g. December 31, 2019) for wellheads but status is no longer showing there. See screenshot below.

![Screen Shot 2020-02-25 at 9 05 52 PM](https://user-images.githubusercontent.com/16269555/75313776-bbb3cd80-5812-11ea-98f2-03d331ef60e3.png)

**Comment by npspringer** [comment]
Status is now added in hover.  We can add any data attributes both to hover and click.  For instance, you'll see that when you click on a bubble, you also get % global production.  Is this good for now, or would you like something else in hover/click windows?

**Comment by mkriss** [comment]
Looks great! – all good for now. (I don't think we need to % global production because that will always be such as small amount.)

**Comment by mkriss** [comment]
One more thing: it appears that rollovers only work for 1 yr now ...

**Comment by npspringer** [comment]
The 1yr layer is now on top, so they will be the first popup across the board since they cover the 1 mo and 24 hr layers.  If you uncheck the 1yr layer, you should get popups for 1 mo, and similarly for the 24 hr layer.

I can switch it back so the 24 hour layer is on top, followed by the 1 mo, then the 1 yr.  Then when you scroll around you'll get a diversity of popups.

**Comment by mkriss** [comment]
Yes, let's switch it back so that you get the diversity of popups.

**Comment by npspringer** [comment]
Done.

**Comment by mkriss** [comment]
Much better. :-)
