### ISSUE TITLE
Carto bubble size bug

### ISSUE THREAD

**Issue by mkriss** [Geofinancial/methanescan#13]
Wells with NA oil/gas production are too small. See, for example, how New Mexico sites compare to Texas sites in the following screenshot.

![Screen Shot 2020-02-24 at 2 09 23 PM](https://user-images.githubusercontent.com/16269555/75199900-2ed91900-5719-11ea-974b-ecc40b922deb.png)

Can we make wells with NA oil/gas production have the same size as wells with 0 oil/gas production?

**Comment by npspringer** [comment]
Right now, they should be the same size as wells with zero oil/gas production, which includes all wellheads outside Texas. If you would like them bigger, we can either 1) simply make the base size of zero/NA wellheads a bit bigger or 2) scale by something else other than production, such the methane score).  Let me know which you would prefer.

**Comment by mkriss** [comment]
For now, I'd go with option 1 – bigger base size.

Regarding option 2, is it possible to infer flow rate – and/or potential climate forcing – from methane score and production?

**Comment by npspringer** [comment]
Okay - option 1 enabled.  Are they big enough now?

**Comment by mkriss** [comment]
Yes, looks good! I opened a new issue #16 to consider how we might adjust this going forward.
