### ISSUE TITLE
Widget label too long

### ISSUE THREAD

**Issue by mkriss** [Geofinancial/methanescan#15]
Label is cropped when presented in [iframe on website](https://data.geofinancial.com/data/). See screenshot below.

![Screen Shot 2020-02-25 at 7 39 57 AM](https://user-images.githubusercontent.com/16269555/75266980-02b8a900-57a8-11ea-9948-6db3d966a6ba.png)

Small font possible for just "(% global production)"?

**Comment by mkriss** [comment]
Nat, What does BOE stand for "(% global BOE)"?

**Comment by npspringer** [comment]
Hey Mark, wasn't able to change font size, again a big limitation of Carto is their widgets are hard to modify.

I changed the label to "% global BOE", which is shorter and actually more descriptive, assuming the reader knows BOE is barrels of oil equivalent.  The other option is "% production", and clarify that it's % global production in the notes.

**Comment by mkriss** [comment]
Got it. I think BOE is a bit cryptic for financial folks. Let's go with "% global prod."

**Comment by npspringer** [comment]
Done, although I think it might still be cut off.  If it is we can try something else.

**Comment by mkriss** [comment]
Ok, great.
