### ISSUE TITLE
Yellow wellheads difficult to see against map

### ISSUE THREAD

**Issue by mkriss** [Geofinancial/methanescan#18]
For example:

![Screen Shot 2020-02-25 at 9 33 24 PM](https://user-images.githubusercontent.com/16269555/75315121-a3de4880-5816-11ea-8500-83e9046d772e.png)

Use brownish-yellow instead of yellow? Scale then becomes: brownish-yellow -> orange -> red.

**Comment by npspringer** [comment]
Changed color template, should be brownish-yellow and easier to see now.

**Comment by mkriss** [comment]
Much better! Well done! All good – get some sleep.
