### ISSUE TITLE
Refine Carto per Mockup

### ISSUE THREAD

**Issue by mkriss** [Geofinancial/methanescan#2]
**Revise Carto per annotated mockup below** (see also non-annotated cleaned up version below)

![Carto mockup_Jan 2020_annotated](https://user-images.githubusercontent.com/16269555/74204165-ebfe4800-4c26-11ea-9d86-1e3d2a0e8abb.png)

**Enhancements For Beta**
- Coverage of continental US
Possibly including Alaska
Possibly excluding a few oil/gas producing states (e.g. Oklahoma, Mississippi, Kentucky)
- Show Peer Score Average per mockup
- Show % of global company production per mockup
Only providing production numbers for wells in Texas
Only providing global production numbers for top 10 companies in Russell 3000 by mkt cap
- Selectable (not just zoomable) by region per mockup
- Enable views by historical data (Now, 1mo, 6mo, 1yr, 3yr, 5yr) per mockup
- Add layers so that data granularity varies by zoom level (worldwide, region, wellhead)
- Carto map should be "Public with a link" ([see this for managing map and dataset privacy](https://carto.com/help/tutorials/managing-map-and-dataset-privacy/)); will be accessible from ["Data" page](https://geofinancial.com/quickstart/) at geofinancial.com
- Change "% Production" to "% Global Production"

**Cleaned up (non-annotated) mockup**

![Carto mockup_Jan 2020_cleanedup r1](https://user-images.githubusercontent.com/16269555/74204173-f587b000-4c26-11ea-829b-64a408b0ec62.png)

//////////////////////////////////////////////////////////////////////////////////////////////////////

Current live version of cartogram accessible via ["Data" page](https://npspringer.carto.com/builder/86ef5c83-3916-44b1-9f28-9d7d46516d2d/embed?state=%7B%22map%22%3A%7B%22ne%22%3A%5B30.977609093348686%2C-102.95013427734376%5D%2C%22sw%22%3A%5B32.73415132036005%2C-99.02252197265626%5D%2C%22center%22%3A%5B31.86122982593092%2C-100.98495483398439%5D%2C%22zoom%22%3A9%7D%2C%22widgets%22%3A%7B%228382a20b-35ad-461b-ac85-a7e836d89a7c%22%3A%7B%22normalized%22%3Atrue%7D%7D%7D) at geofinancial.com. You must use your geofinancial.com email account to log in.

**Comment by npspringer** [comment]
Completed steps:
- Coverage of continental US
- Show Peer Score Average per mockup
- Show % of global company production per mockup (Only providing production numbers for wells in Texas and only providing global production numbers for top 10 companies in Russell 3000 by mkt cap
- Enable views by historical data (Now, 1mo, 1yr) per mockup
- Carto map should be "Public with a link" (see this for managing map and dataset privacy); will be accessible from "Data" page at geofinancial.com
- Change "% Production" to "% Global Production"

**Comment by mkriss** [comment]
Excellent, Nat! Well done!!! I'm closing this issue, moving "Enhancements for Production" to new issue #11
