### ISSUE TITLE
Simple access control for provisioning different levels of subscriptions

### ISSUE THREAD

**Issue by mkriss** [Geofinancial/methanescan#7]
**Simple low-volume approach**
• Access control per directory (worst case an admin page for each area – would be ok in low volume scenario)
• Three directories, one for each product
– Trial
– Global
– Premium Add-On

**Notes**
1) It's conceivable that one customer would subscribe to all 3 products.
2) Probably not worth investing at this stage in a single admin page since:
– Likely low volume
– May end up distributing via platform providers (although probably not exclusively so)
– We may find that Google auth is not acceptable for some large firms

**Defer**
• More work: single admin page that's aware of all levels (e.g. Auth0 path and proper role based access control)

**Comment by mkriss** [comment]
Hey Jess,

I'm inclined to keep this simple, for the reasons outlined in revised description above. Do we need to discuss in more detail? Is March 31st deadline do-able?

**Comment by jkriss** [comment]
Yeah, this is doable. It's probably just as easy to put three admin widgets on the same page.

With a little extra logic, we should be able to show the links for the products that each person has purchased after they log in.

No problem with people signing up for multiple–they'll log in once, and they'll be able to access whatever they have permission for.

**Comment by mkriss** [comment]
Perfect! :-)

**Comment by jkriss** [comment]
Just added this. I've kept the existing beta list and admin page to avoid disruption.

There are now three new admin pages, linked to from the main admin page (and each other). On the main page, after logging in, it will display links for any of the three subscriptions that the current user can access.

**Comment by jkriss** [comment]
Oh, one warning: Don't try to edit the different lists from multiple tabs. Right now, each page loads the entire access list, and writes back changes, so it'll overwrite the other beta lists if they were changed in between. As long as you don't have multiple admin pages open at once you should be fine.

**Comment by mkriss** [comment]
Cool! ... and thanks for the warning.

Can you do the following?

1) Change link names:

Access MethaneScan® Trial (instead of "Trial Data")
Access MethaneScan® Global (instead of "Global Data")
Access MethaneScan® Premium Add-On (instead of "Premium")

2) Copy iframe at https://data.geofinancial.com/data/ to https://data.geofinancial.com/trial/

3) Once above has been completed and verified working, let's delete "Data is here" line. (I've already copied all Beta List users to Trial List Users).

Thanks! This is awesome. :-)

**Comment by jkriss** [comment]
1 and 2 are done, will do 3 when you confirm we're good to go.

**Comment by mkriss** [comment]
Good to go!

One question: In another browser I was logged in as mkriss@gmail.com. Even after I logged out, I was still recognized as mkriss@gmail.com – which makes sense. As a user, is it possible for me to change my account to a different Google account?

**Comment by jkriss** [comment]
What do you mean by "still recognized"? When I log out and log back in, I see the Google login screen which lets me choose which Google account I want to use.

I removed the "data is here" link.

**Comment by mkriss** [comment]
That's not what I'm seeing. For me, it remembers my prior login and doesn't give me the option to choose which Google account I want to use.

Yes, I see "data is here" link is gone, thanks.

**Comment by jkriss** [comment]
When you say "it remembers" do you mean that you don't see the Google account selection at all, but you just come straight back to our page?

**Comment by mkriss** [comment]
Yes.

**Comment by jkriss** [comment]
It looks like there is an optional parameter that we can send to Google that will force the account selection step on each login. Presumably that's what you want?

**Comment by mkriss** [comment]
Yes, that's what we want.

**Comment by jkriss** [comment]
How about now?

**Comment by mkriss** [comment]
Yep! All good. :-)

One anomaly, which is probably fine. If you log in with an unauthorized email account, you still see Release Notes (but no access to any data). I'd rather non-subscribers don't see the Release Notes but I doubt many people will encounter that case.

**Comment by mkriss** [comment]
Case closed. Bravo!
