### ISSUE TITLE
Update Carto link on https://data.geofinancial.com/data/

### ISSUE THREAD

**Issue by mkriss** [Geofinancial/methanescan#9]
New Carto public link: 

https://geofinancial.carto.com/builder/eec6495a-bc53-4dcf-ac7e-7355397e3164/embed

 [Note: "here" in "Data is here" should be highlighted in same fashion to indicate active hyperlink]

If possible on the same page underneath this link please add this hyperlink:

[Release Notes](https://geofinancial.com/release-notes)

**Comment by npspringer** [comment]
Hi Mark, just an FYI, this link includes the zoom to the LA basin we were just looking at. 
The shorter and Texas centric link is simply the part ending with "embed": [](https://geofinancial.carto.com/builder/eec6495a-bc53-4dcf-ac7e-7355397e3164/embed)

**Comment by mkriss** [comment]
Hi Nat,

Got it – corrected, thanks!

--mark

<https://app.grooveapp.com/url/dbuxvcv3x3riyekaluufq/aHR0cHM6Ly9nZW9maW5hbmNpYWwuY29tL2NvbW11bml0eS8%3D>

*Mark Kriss  *|  CEO  |  Geofinancial Analytics
<https://app.grooveapp.com/url/dbuxvcv3x3riyekaluufq/aHR0cHM6Ly9nZW9maW5hbmNpYWwuY29tL2NvbW11bml0eS8%3D>
  |  +1 612.222.9195 x3

**Comment by jkriss** [comment]
Done

**Comment by mkriss** [comment]
Great! 

Is it easy to add this hyperlink below "Data is here"?

[Release Notes](https://geofinancial.com/release-notes)

... or does that require solution to #7?

**Comment by mkriss** [comment]
Also, is it possible to widen the Carto iframe so that it spans more of the page?

For example, controls on right are a bit cropped. See screenshot below.

![Screen Shot 2020-02-22 at 9 45 14 PM](https://user-images.githubusercontent.com/16269555/75104324-caa14280-55bc-11ea-906a-0af797a1c732.png)

**Comment by jkriss** [comment]
Adjusted the size, added the link.

One small nit: "Release notes" typically means specific features, fixes, etc. particular to a given release, not more general FAQ style info.

**Comment by mkriss** [comment]
Looks great, thanks! 

Here's actual [release notes content](https://geofinancial.com/quickstart#7). This sort of fits "release notes", doesn't it?

**Comment by jkriss** [comment]
I think it's more of a FAQ, but it's not a big deal.

**Comment by mkriss** [comment]
Are we looking at the same content? This page – now updated: https://geofinancial.com/release-notes

As contrasted with [QuickStart Guide](https://geofinancial.com/quickstart/).

**Comment by jkriss** [comment]
Ooooh. Yeah, that's more like it.

**Comment by mkriss** [comment]
Ok, great. :-) 

I guess to keep from clipping "Company (% of Global Production)" label we'll need to use smaller fonts? Can't widen the iframe enough to fix that?

![Screen Shot 2020-02-24 at 9 08 14 PM](https://user-images.githubusercontent.com/16269555/75216797-0f0e1900-574a-11ea-8e8e-bcfde480c283.png)

**Comment by jkriss** [comment]
I did try that, but it has to go so wide that you can't see the whole map on a single screen. I figured it was better to have the truncated text than to have to scroll to see the map.

**Comment by mkriss** [comment]
Okedoke. Agreed.

**Comment by npspringer** [comment]
Apologies guys, but had some issues when updating the dataset and accidentally deleted the cartogram.  Here's the link to the new one: 

https://geofinancial.carto.com/builder/79ca1050-bf82-41ee-b4b7-63ef9ab510c8/embed

Should be exactly the same as the old one, but with the new data.  Sorry if that messes up the code embedding it in the website, release notes, etc. (FYI - in the next round, we can host our data externally so maps update automatically with new data... I tried to do this with the box connector on carto, but it has limited functionality and wasn't able access Daniel's files through their interface).

**Comment by jkriss** [comment]
Done

**Comment by mkriss** [comment]
Awesome! :-)
